### ISSUE TITLE
ERR_BADAUTH

### ISSUE THREAD

**Issue by marcosknudsen** [jctrvlr/twitchPS#27]
Cant auth successfully, How can I get an usable token?

TwitchPS -- 1/4/2022, 3:27:06 AM -- in _wait() --  Connected
TwitchPS -- 1/4/2022, 3:27:07 AM -- in _connect() --  { type: 'RESPONSE', error: 'ERR_BADAUTH', nonce: 'gDhGnfmn6' }
events.js:366
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  origin: 'Error caught in _connect() on message',
  error: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
    origin: 'addTopic()',
    error: 'ERR_BADAUTH',
    topic: 'channel-points-channel-v1.elk4nu'
  })
      at TwitchPS.emit (events.js:364:17)
      at TwitchPS._handleError (e:\Coding\node_modules\twitchps\main.js:793:10)
      at Object.reject (e:\Coding\node_modules\twitchps\main.js:860:20)
      at WebSocket.<anonymous> (e:\Coding\node_modules\twitchps\main.js:88:44)
      at WebSocket.emit (events.js:375:28)
      at Receiver.receiverOnMessage (e:\Coding\node_modules\ws\lib\websocket.js:834:20)
      at Receiver.emit (events.js:375:28)
      at Receiver.dataMessage (e:\Coding\node_modules\ws\lib\receiver.js:437:14)
      at Receiver.getData (e:\Coding\node_modules\ws\lib\receiver.js:367:17)
      at Receiver.startLoop (e:\Coding\node_modules\ws\lib\receiver.js:143:22) {
    code: 'ERR_UNHANDLED_ERROR',
    context: {
      origin: 'addTopic()',
      error: 'ERR_BADAUTH',
      topic: 'channel-points-channel-v1.elk4nu'
    }
  },
  topic: null
})
    at TwitchPS.emit (events.js:364:17)
    at TwitchPS._handleError (e:\Coding\node_modules\twitchps\main.js:793:10)
    at WebSocket.<anonymous> (e:\Coding\node_modules\twitchps\main.js:146:14)
    at WebSocket.emit (events.js:375:28)
    at Receiver.receiverOnMessage (e:\Coding\node_modules\ws\lib\websocket.js:834:20)
    at Receiver.emit (events.js:375:28)
    at Receiver.dataMessage (e:\Coding\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (e:\Coding\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (e:\Coding\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (e:\Coding\node_modules\ws\lib\receiver.js:78:10) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    origin: 'Error caught in _connect() on message',
    error: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
      origin: 'addTopic()',
      error: 'ERR_BADAUTH',
      topic: 'channel-points-channel-v1.elk4nu'
    })
        at TwitchPS.emit (events.js:364:17)
        at TwitchPS._handleError (e:\Coding\node_modules\twitchps\main.js:793:10)
        at Object.reject (e:\Coding\node_modules\twitchps\main.js:860:20)
        at WebSocket.<anonymous> (e:\Coding\node_modules\twitchps\main.js:88:44)
        at WebSocket.emit (events.js:375:28)
        at Receiver.receiverOnMessage (e:\Coding\node_modules\ws\lib\websocket.js:834:20)
        at Receiver.emit (events.js:375:28)
        at Receiver.dataMessage (e:\Coding\node_modules\ws\lib\receiver.js:437:14)
        at Receiver.getData (e:\Coding\node_modules\ws\lib\receiver.js:367:17)
        at Receiver.startLoop (e:\Coding\node_modules\ws\lib\receiver.js:143:22) {
      code: 'ERR_UNHANDLED_ERROR',
      context: {
        origin: 'addTopic()',
        error: 'ERR_BADAUTH',
        topic: 'channel-points-channel-v1.elk4nu'
      }
    },
    topic: null
  }
}

**Comment by marcosknudsen** [comment]
Already fixed, ty
